name: Build cnc_firmware

on:
#  push:
#    branches:
#      -main
#    paths: Configurations/**
#    tags:
#      - "v*.*.*"
#    paths-ignore: |
#      MarlinFirmware/**
#      examples_gcode/**
#  pull_request:
#    branches:
#      -main
#    paths: Configurations/**

  workflow_dispatch:  
    inputs:
      board:
        required: true
        default: mega2560
        description: Board environment  
      config:
        required: true
        default: https://github.com/MarlinFirmware/Configurations/config/default
        description: Configuration directory
      repository_1:
        required: true
        default: MarlinFirmware/Marlin
        description: Marlin Repository
      ref:
        description: Branch / tag / SHA to checkout
  
#permissions:
#  actions: read|write|none
#  checks: read|write|none
#  contents: read|write|none
#  deployments: read|write|none
#  id-token: read|write|none
#  issues: read|write|none
#  discussions: read|write|none
#  packages: read|write|none
#  pages: read|write|none
#  pull-requests: read|write|none
#  repository-projects: read|write|none
#  security-events: read|write|none
#  statuses: read|write|none
  
   # ${{ fromJson(
#     #   github.event_name == 'schedule' && '["bugfix-2.1.x"]' ||
#     #   github.event_name == 'pull_request' && '["bugfix-2.1.x", "2.1.2"]' ||
#     #   '["2.1.2"]') }}      
#  machine: ramps14

jobs:
  preset_values:
  
    env:
      matrix: 
        branch: 
          - "2.1.2"
        machine: 
          - ramps14 
          - ramps_16

    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: create_json
        run: |
cat > /etc/exports << CONFIG2
# write settings for NFS exports
/home 192.168.1.0/255.255.255.0(rw,no_root_squash)
/               master(rw) trusty(rw,no_root_squash)
/projects       proj*.local.domain(rw)
/usr            *.local.domain(ro) @trusted(rw)
/home/joe       pc001(rw,all_squash,anonuid=150,anongid=100)
/pub            *(ro,insecure,all_squash)
/srv/www        -sync,rw server @trusted @external(ro)
/foo            2001:db8:9:e54::/64(rw) 192.0.2.0/24(rw)
/build          buildhost[0-9].local.domain(rw)
CONFIG2        
        
        
      
      
      - id: set-matrix
        run: 
          echo "${{ env.matrix }}" >> $GITHUB_OUTPUT
      - name: Install PlatformIO Core
        run: |
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "${{ toJson(env.matrix) }}"
      
  test:
    name: "Run unit tests"
    needs: preset_values

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}
      V1_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

    strategy:
      fail-fast: false
      matrix:
        JSON_ARRAY: ${{ fromJson(needs.preset_values.outputs.matrix) }}

    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    # Cloning my repository to the runner:  
      - uses: actions/checkout@v3  
        name: "Checkout source repository"
        with:
          path: ${{ matrix.machine }}/**        

  build:
    name: Build firmware
    needs: [preset_values, test]

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}
      V1_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

    strategy:
      fail-fast: false
      matrix:
        JSON_ARRAY: ${{ fromJson(needs.preset_values.outputs.matrix) }}

    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
           
    steps:
      # Cloning my repository to the runner:  
      - uses: actions/checkout@v3  
        name: Checkout source repository
        with:
          path: ${{ matrix.machine }}/**
        
      # Cloning repository to the runner:
      - uses: actions/checkout@v3
        name: Checkout MarlinFirmware
        with:
          repository: MarlinFirmware/Marlin
          ref: ${{ matrix.branch }}
          path: Marlin 
          clean: true
#           fetch-depth: 1
    
      # Install Python
      - uses: actions/setup-python@v4
        name: Select Python 3.10
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified      
      # Install PlatformIO Core    
      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          pio lib --global install olikraus/U8glib@^1.19.1       

      # Copy config files Marlin folder
      - name: Copy configuration
        run: |
          whoami
          cp -a ${{ matrix.machine }}/. Marlin/Marlin/
          cd Marlin/Marlin
          ls -la

      # Compile firmware
      - name: Compile firmware
        run: |
          pio run --project-dir Marlin --environment mega2560

      # Prepare assets
      - name: Add artifacts to publish to the temp folder
        run: |
          mkdir -p downloads/pio
          ls -la
          cp -a Marlin/.pio/. downloads/
          ls -la -R downloads

      - name: 'Zip files'
        run: zip -r ${{ matrix.machine }}-${{ matrix.branch }}_artifact.zip downloads
      - name: 'Upload artifact for deployment job'
        id: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.machine }}-${{ matrix.branch }}_artifact
          path: |        
            ${{ matrix.machine }}-${{ matrix.branch }}_artifact.zip     
            *.hex
            firmware*  

      - name: 'list folder'
        run: |
          ls -la
          echo "pokus"

  deploy:
    name: Release firmware
    needs: [preset_values, build]

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}
      V1_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

    strategy:
      fail-fast: false
      matrix:
        JSON_ARRAY: ${{ fromJson(needs.preset_values.outputs.matrix) }}

    defaults:
      run:
        shell: bash    
    runs-on: ubuntu-latest
    
 #   permissions:
 #     contents: write    
      
    steps:
      - name: Downloads artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.machine }}-${{ matrix.branch }}_artifact

      - name: "list folder"
        run: |
          ls -la    
          echo "pokus" 

      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: "list folder"
        run: |
          ls -la    
          echo "pokus"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ matrix.machine }}-${{ matrix.branch }}_artifact.zip
          asset_name: fw-${{ matrix.machine }}-${{ matrix.branch }}.zip
          asset_content_type: application/zip

      - name: "list folder"
        run: |
          ls -la    
          echo "pokus"
    
      - name: Show files changed
        run: |
          ls -la -R  ./
          ls -la -R  $HOME/
        

    
