name: Build cnc_firmware

on:
  push:
    branches:
    - main
    - release/*
    
jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      MARLIN_VERSION: ${{ matrix.branch }}
#      CONFIG_NAME: ${{ matrix.machine }}
#    name: ${{ matrix.machine }}-${{ matrix.branch }}
    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch: ${{ fromJson(
          github.event_name == 'schedule' && '["bugfix-2.1.x"]' ||
          github.event_name == 'pull_request' && '["bugfix-2.1.x", "2.1.2"]' ||
          '["2.1.2"]') }}
        machine:
        - cnc_stroj_v2
    steps:
    # First, cancel unfinished jobs.
      - uses: technote-space/auto-cancel-redundant-job@v1

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified   
          
      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
          platformio update
          pio lib --global install olikraus/U8glib@^1.19.1  
          pio pkg install --global --platform symlink://.
          
      - name: Check out MarlinBuilder
        uses: actions/checkout@v3

     - name: Check out MarlinFirmware
       uses: actions/checkout@v3
       with:
         repository: MarlinFirmware/Marlin
         ref: ${{ matrix.branch }}
         path: Marlin
         clean: true
         fetch-depth: 1

      - name: Upload src artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.machine }}-${{ matrix.branch }}
          path: |
            Marlin_*.zip
          
      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.machine }}-${{ matrix.branch }}
          path: |
            firmware*
            Marlin_*.zip          
          
      - name: Upload Marlin-${{ matrix.machine }}-${{ matrix.branch }}.zip to release
        if: ${{ github.event_name == 'release' }}
          uses: actions/upload-release-asset@v1
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Marlin-Release.zip
          asset_name: ${{ matrix.machine }}-${{ matrix.branch }}.zip
          asset_content_type: application/zip          
          
